apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.local
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: visaas-super-admin-ui
            port:
              number: 80
      - path: /fuse
        pathType: Prefix
        backend:
          service:
            name: visaas-fuse-ui-service
            port:
              number: 80
